#!/usr/bin/env python3.6

# A sample training component that trains a simple scikit-learn decision tree model.
# This implementation works in File mode and makes no assumptions about the input file names.
# Input is specified as CSV with a data point in each row and the labels in the first column.

from __future__ import print_function

import os
import json
import pickle
import sys
import traceback

import pandas as pd
import numpy as np

from sklearn import preprocessing
from sklearn.utils import shuffle
from sklearn import ensemble

RATIO_FOR_TRAINING = 0.8

# These are the paths to where SageMaker mounts interesting things in your container.
prefix = '/opt/ml/'

input_path = prefix + 'input/data'
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')
param_path = os.path.join(prefix, 'input/config/hyperparameters.json')

# This algorithm has a single channel of input data called 'training'. Since we run in
# File mode, the input files are copied to the directory specified here.
channel_name='training'
training_path = os.path.join(input_path, channel_name)

def convertHyperParams(params):
    if 'n_estimators' in params:
        params['n_estimators'] = int(params['n_estimators'])

    if 'max_depth' in params:
        params['max_depth'] = int(params['max_depth'])

    if 'min_samples_split' in params:
        params['min_samples_split'] = int(params['min_samples_split'])

    if 'learning_rate' in params:
        params['learning_rate'] = float(params['learning_rate'])

    if 'verbose' in params:
        params['verbose'] = params['verbose']

# The function to execute the training.
def train():
    print('Starting the training.')
    try:
        # Read in any hyperparameters that the user passed with the training job
        with open(param_path, 'r') as tc:
            trainingParams = json.load(tc)

        # Take the set of files and read them all into a single pandas dataframe
        input_files = [ os.path.join(training_path, file) for file in os.listdir(training_path) ]
        if len(input_files) == 0:
            raise ValueError(('There are no files in {}.\n' +
                              'This usually indicates that the channel ({}) was incorrectly specified,\n' +
                              'the data specification in S3 was incorrectly specified or the role specified\n' +
                              'does not have permission to access the data.').format(training_path, channel_name))

        data = [pd.read_csv(file, header=None) for file in input_files]
        data = pd.concat(data)

        ids = data.iloc[:, 0]
        vars = data.iloc[:, 1:-1]
        target = data.iloc[:, -1]

        #
        # set up label encoders for categorical vars
        #
        encoders = {}
        # add 'unknown' element so that novel values can be handled gracefully
        callTypes = np.append(vars.iloc[:, 7].unique(), ["<unknown>"])
        langs = np.append(vars.iloc[:, 8].unique(), ["<unknown>"])
        encoders['callType'] = preprocessing.LabelEncoder().fit(callTypes)
        encoders['language'] = preprocessing.LabelEncoder().fit(langs)

        vars.iloc[:, 7] = encoders['callType'].transform(vars.iloc[:, 7])
        vars.iloc[:, 8] = encoders['language'].transform(vars.iloc[:, 8])

        #
        # build and train the model
        #

        ids, X, y = shuffle(ids, vars, target, random_state=13)
        X = X.astype(np.float32)
        offset = int(X.shape[0] * RATIO_FOR_TRAINING)
        X_train, y_train = X[:offset], y[:offset]
        X_test, y_test, ids_test = X[offset:], y[offset:], ids[offset:]

        # Do any necessary type conversions
        convertHyperParams(trainingParams)
        print("training model with " + str(len(X_train)) + " points")

        # Now use scikit-learn's decision tree classifier to train the model.
        clf = ensemble.GradientBoostingRegressor(**trainingParams)
        clf = clf.fit(X_train, y_train)

        # save the model
        with open(os.path.join(model_path, 'boosted-trees-model.pkl'), 'wb') as out:
            pickle.dump(clf, out)

        # save the encoders
        with open(os.path.join(model_path, 'boosted-trees-encoders.pkl'), 'wb') as out:
            pickle.dump(encoders, out)

        print('Training complete.')
    except Exception as e:
        # Write out an error file. This will be returned as the failureReason in the
        # DescribeTrainingJob result.
        trc = traceback.format_exc()
        with open(os.path.join(output_path, 'failure'), 'w') as s:
            s.write('Exception during training: ' + str(e) + '\n' + trc)
        # Printing this causes the exception to be in the training job logs, as well.
        print('Exception during training: ' + str(e) + '\n' + trc, file=sys.stderr)
        # A non-zero exit code causes the training job to be marked as Failed.
        sys.exit(255)

if __name__ == '__main__':
    train()

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)
